version: "2.0"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracle11
    shm_size: 1g # 共有メモリは1GB以上にしないとコンテナ起動時にエラー発⽣
    environment:
    - TZ=Asia/Tokyo
    - LANGUAGE=ja_JP.ja
    - LANG=ja_JP.UTF-8
    - NLS_LANG=Japanese_Japan.AL32UTF8 # sqlplusの⽇本語化⽤
    - ORACLE_PWD=oracle # sys,systemのパスワード
    - ORACLE_SID=XE
    - ORACLE_PDB=pdb1
    ports:
    - 1521:1521
    volumes:
    - ./oradata:/opt/oracle/oradata # データの永続化